import { AppShell, Container, Header } from '@mantine/core';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { PropsWithChildren, useEffect } from 'react';
import Appheader from './header';
import { useUser } from './userProvider';

const Layout: React.FC<PropsWithChildren<unknown>> = ({ children }) => {
  const [user] = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.push('/signin');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);

  return (
    <>
      <Head>
        <title>Manga Bai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        header={
          <Header height={60} p="xs">
            <Appheader />
          </Header>
        }
      >
        <Container>{children}</Container>
      </AppShell>
    </>
  );
};

export default Layout;
