import { AppShell, Container, Footer, Header } from '@mantine/core';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { PropsWithChildren, useEffect } from 'react';
import Appheader from './header';
import { useUser } from './userProvider';

const Layout: React.FC<PropsWithChildren<unknown>> = ({ children }) => {
  const [user] = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.push('/signin');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);

  return (
    <>
      <Head>
        <title>Manga Bai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        header={
          <Header
            height={60}
            py="xs"
            sx={{ paddingRight: 'var(--removed-scroll-width, 0px)' }}
          >
            <Appheader />
          </Header>
        }
        footer={
          <Footer height={180} sx={{ zIndex: 0 }}>
            <Container size="xl">Test</Container>
          </Footer>
        }
        styles={theme => ({
          main: {
            zIndex: 1,
            marginBottom: 180,
            paddingBottom: theme.spacing.md,
            backgroundColor:
              theme.colorScheme === 'dark'
                ? theme.colors.dark[8]
                : theme.colors.gray[0]
          }
        })}
        fixed
      >
        <Container size="xl">{children}</Container>
      </AppShell>
    </>
  );
};

export default Layout;
